name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install compiling tools
      run: brew install ninja cmake protobuf pyenv
    - name: install python
      run: |
        pyenv install 3.7.0
        pyenv global 3.7.0
        pyenv rehash
    - name: build llvm/mlir
      run: |
        cd ..
        git clone https://github.com/llvm/llvm-project.git
        cd llvm-project
        git checkout 9c94908320549a1a2328c758d6bbb694466021e7
        cd ..
        pwd
        mkdir llvm-project/build
        cd llvm-project/build
        cmake -G Ninja ../llvm \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_BUILD_EXAMPLES=ON \
            -DLLVM_TARGETS_TO_BUILD="host" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON
        cmake --build . --target -- ${MAKEFLAGS}
        cmake --build . --target check-mlir
    - name: build onnx-mlir
      run: |
        pwd
        cd ..
        pwd
        export LLVM_PROJ_SRC=$(pwd)/llvm-project/
        export LLVM_PROJ_BUILD=$(pwd)/llvm-project/build
        mkdir onnx-mlir/build && cd onnx-mlir/build
        cmake -G Ninja ..
        cmake --build .
        export LIT_OPTS=-v
        cmake --build . --target check-onnx-lit
    - name: print disk usage
      run: |
        pwd
        cd ..
        du -hs onnx-mlir
        du -hs onnx-mlir/build
        du -hs llvm-project
        du -hs llvm-project/build
