name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: install tools that are needed for compilation
      run: | 
        brew install ninja protobuf
    - name: clone MLIR
      run: |
        cd ~/onnx-mlir
        sh $GITHUB_WORKSPACE/utils/clone-mlir.sh
    - name: cache MLIR binaries
      id: cache-mlir
      uses: actions/cache@v2
      env:
        cache-name: cache-mlir-build-directory
      with:
        path: ~/onnx-mlir/llvm-project/build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('$GITHUB_WORKSPACE/utils/clone-mlir.sh') }}
    - name: build MLIR
      if: steps.cache-mlir.outputs.cache-hit != 'true'
      run: |
        cd ~/onnx-mlir
        sh $GITHUB_WORKSPACE/utils/build-mlir.sh
    - name: build onnx-mlir
      run: |
        cd ~/onnx-mlir
        # sh $GITHUB_WORKSPACE/utils/install-onnx-mlir.sh
        export LLVM_PROJ_SRC=$(pwd)/llvm-project/
        export LLVM_PROJ_BUILD=$(pwd)/llvm-project/build
        mkdir onnx-mlir/build && cd onnx-mlir/build
        cmake -G Ninja ..
        cmake --build .
        # export LIT_OPTS=-v
        # cmake --build . --target check-onnx-lit
    - name: print disk usage
      run: |
        cd ~/onnx-mlir
        du -hs onnx-mlir
        du -hs onnx-mlir/build
        du -hs llvm-project
        du -hs llvm-project/build
