name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install compiling tools
      run: brew install ninja cmake protobuf pyenv
    - name: install python
      run: |
        pyenv install 3.7.0
        pyenv global 3.7.0
        pyenv rehash
    - name: build llvm/mlir
      run: |
        cd $GITHUB_WORKSPACE/..
        sh $GITHUB_WORKSPACE/utils/clone-mlir.sh
        pwd
        sh $GITHUB_WORKSPACE/utils/build-mlir.sh
    - name: build onnx-mlir
      run: |
        pwd
        export LLVM_PROJ_SRC=$(pwd)/../llvm-project/
        export LLVM_PROJ_BUILD=$(pwd)/../llvm-project/build
        mkdir onnx-mlir/build && cd onnx-mlir/build
        cmake -G Ninja ..
        cmake --build .
        export LIT_OPTS=-v
        cmake --build . --target check-onnx-lit
    - name: print disk usage
      run: |
        pwd
        ls
        cd ..
        ls
        du -hs onnx-mlir
        du -hs onnx-mlir/build
        du -hs llvm-project
        du -hs llvm-project/build
