name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install tools that is needed for compilation
      run: | 
        brew install ninja protobuf pyenv
        pyenv install 3.7.0
        pyenv shell 3.7.0
        pyenv rehash
        export PATH=$$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH
    - name: print python versions
      run: |
        which python
        which python3
    - name: build MLIR
      run: |
        which python
        which python3
        cd $GITHUB_WORKSPACE/..
        sh $GITHUB_WORKSPACE/utils/clone-mlir.sh
        sh $GITHUB_WORKSPACE/utils/build-mlir.sh
    - name: build onnx-mlir
      run: |
        cd $GITHUB_WORKSPACE/..
        export LLVM_PROJ_SRC=$(pwd)/llvm-project/
        export LLVM_PROJ_BUILD=$(pwd)/llvm-project/build
        mkdir onnx-mlir/build && cd onnx-mlir/build
        cmake -G Ninja ..
        cmake --build .
        export LIT_OPTS=-v
        cmake --build . --target check-onnx-lit
    - name: print disk usage
      run: |
        cd $GITHUB_WORKSPACE/..
        du -hs onnx-mlir
        du -hs onnx-mlir/build
        du -hs llvm-project
        du -hs llvm-project/build
